# -*- coding: utf-8 -*-
"""data_cleaner4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MzvrWuFGwHs9MmCxhLXmf8sxEwHJQxuB
"""

import pandas as pd
# Load file
try:
  df = pd.read_excel('grades_sample.xlsx')
except FileNotFoundError:
  print("File not found. Make sure it's uploaded.")#Stop here if file not found
  raise
#Data cleaning
try:
  df = df.drop_duplicates()
  df['Math Score'] = df['Math Score'].fillna(df['Math Score'].mean().round(0)).astype(int)
  df['Physics Score'] = df['Physics Score'].fillna(df['Physics Score'].mean().round(0)).astype(int)
except KeyError:
  print('Column not found')
  raise
# save to new file
df.to_excel('cleaned_grades_sample.xlsx', index = False)
print("Done! Check cleaned_grades_sample.xlsx")

