# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKNSn7UY-MrSDBIlFfb_M4FlzDjzlxdH
"""

import pandas as pd
# Load file
try:
  df = pd.read_excel('grades_sample.xlsx')
except FileNotFoundError:
  print('File not found, ensure that it is uploaded.')
  raise #stop here

try:
  # data cleaning
  df = df.drop_duplicates()
  df['Math Score'] = df['Math Score'].fillna(df['Math Score'].mean().round(0)).astype(int)
  # summary
  stats = df.describe().round(1).drop(index = ['25%','50%','75%']).rename(columns = {'Math Score':'Math','Physics Score':'Physics'})
  # count of grades
  def calc_grades(row):
    if row >= 70:
      return 'A'
    elif row >= 60:
      return 'B'
    elif row >= 50:
      return 'C'
    else:
      return 'D'
  math_scores = df['Math Score'].apply(calc_grades).value_counts()
  physics_scores = df['Physics Score'].apply(calc_grades).value_counts()
  grades = pd.DataFrame({'Math':math_scores,'Physics':physics_scores}).fillna(0)
  summary = pd.concat([grades,stats],axis = 'index')
except KeyError:
  print('Invalid key.')
  raise
summary.to_excel('grades_sample_summary.xlsx')
print('file grades_sample_summary.xlsx created.')