# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJK8QCrA-5ygG7KCZAqhbqbSSV9bCDl_
"""

import pandas as pd
# Load files
try:
  df_hours = pd.read_excel('employee_hours_log.xlsx').set_index('EmployeeID')
  df_department = pd.read_excel('employee_department.xlsx').set_index('EmployeeID')
except FileNotFoundError:
  print(f"File not found. Make sure it's uploaded.")
  raise # stop if error
except Exception as e:
  print(f'File not found: {e}')
  raise
# Data cleaning
try:
  df_hours = df_hours.drop_duplicates()# Remove duplicates
  df = pd.concat([df_hours,df_department],axis = 'columns') # Merge both dataframe
  average_hours = df.groupby('Department').Hours.mean() # Average hours table
  department = df.loc[df[df.Hours.isna()].index].Department.item() # department of missing values
  df.Hours = df.Hours.fillna(average_hours.loc[department]) # Replace missing values with average hours by department
  # Add column Overtime
  def overtime(value):
      if value > 40:
        return 'Yes'
      else:
        return 'No'
  df['Overtime'] = df.Hours.apply(overtime)
  df.to_excel('merged_employee_report.xlsx') # Saves merged file
  # Create pivot table,total hours and overtime count
  df = pd.concat([df.groupby('Department').Hours.sum(),
                  df.loc[df.Overtime == 'Yes'].groupby('Department').Overtime.count()],axis = 'columns')
  # data cleaning for pivot table
  df = df.fillna(0).astype(int)
  df.to_excel('employee_pivot_table.xlsx') # Saves pivot table
except KeyError as e:
  print(f'Column not found: {e}')
  raise # stop if error
except Exception as e:
  print(f'Other error: {e}')
  raise
print('Files merged_employee_report.xlsx and employee_pivot_table.xlsx created')