# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJK8QCrA-5ygG7KCZAqhbqbSSV9bCDl_
"""

import pandas as pd
import matplotlib.pyplot as plt
# Load file
try:
  df = pd.read_excel('stock.xlsx')
except FileNotFoundError:
  print(f"File not found. Make sure it's uploaded.")
  raise # Stop if error
except Exception as e:
  print(f'File not found: {e}')
  raise
try:
  # Data Cleaning
  df = df.drop(index = df.loc[df.Stock < 0].index) # Removes negative stock
  df = df.drop(index = df.loc[df.Price.isna()].index) # Removes missing price
  df.Item = df.Item.drop_duplicates() # Removes duplicate items
  # Add discount column
  def discount(value):
    if value < 20:
      return 10
    else:
     return 0
  df['Discount(%)'] = df.Stock.apply(discount)
  df.to_excel('new_stock.xlsx',index = False) # Saves cleaned file
  # Calculate total value
  df['total_value'] = df.Stock * df.Price
  totals = df.groupby('Category').total_value.sum()
  # Plot bar chart total values by category
  totals.plot(x='Category', y='Total Value', kind='bar')
  plt.title('Total Value per Category')
  plt.xlabel('Category')
  plt.ylabel('Total Value')
  plt.tight_layout()
  plt.savefig('value_chart.png') # Saves plot image
except KeyError as e:
  print(f'Column not found: {e}')
  raise # Stop if error
except Exception as e:
  print(f'Other error: {e}')
  raise
print('Files new_stock.xlsx and value_chart.png created')
