# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IAdoKfiAJz3bsrVfrbI7ZG8F4Ry-VYMF
"""

import pandas as pd
# Load file
try:
  df = pd.read_excel('Task1.xlsx')
except FileNotFoundError:
  print(f"File not found. Make sure it's uploaded")
  raise
except Exception as e:
  print(f"File not found: {e}")
  raise
try:
  # Data cleaning
  df = df.drop_duplicates()
  df.Quantity = df.Quantity.fillna(0).astype(int)
  df.Price = df.Price.fillna(df.Price.mean()).astype(int)
  # Add new column revenue
  df['Revenue'] = df.Quantity * df.Price
except KeyError as e:
  print(f"Column not found: {e}")
  raise
except Exception as e:
  print(f'Other error: {e}')
df.to_excel('cleaned_Task1.xlsx')
print('File cleaned_Task1 created')